# ---------- Overriding hydra default configs ----------
hydra:
  job:
    name: train
    chdir: true
  run:
    dir: output/${hydra.job.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}

defaults:
  - _self_
  - dir: dir
  - model: EfficientNetB1

n_epochs: 8
train_batch_size: 32
valid_batch_size: 256
scheduler: "CosineAnnealingLR"
lr: 1e-4
min_lr: 1e-6
T_max: 500
weight_decay: 1e-6
fold: 0
n_folds: 5
n_accumulates: 1

