# ---------- Overriding hydra default configs ----------
hydra:
  job:
    name: train
    chdir: true
  run:
    dir: output/${hydra.job.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}

defaults:
  - _self_
  - dir: dir

n_epochs: 5
img_size: 384
model_name: "tf_efficientnet_b1"
# https://www.kaggle.com/models/timm/tf-efficientnet/PyTorch/tf-efficientnet-b0/1
checkpoint_path: "/kaggle/input/tf-efficientnet/pytorch/tf-efficientnet-b1/1/tf_efficientnet_b1_aa-ea7a6ee0.pth"
train_batch_size: 64
valid_batch_size: 128
scheduler: "CosineAnnealingLR"
lr: 1e-4
min_lr: 1e-6
T_max: 500
weight_decay: 1e-6
fold: 0
n_folds: 5
n_accumulates: 1

