# ---------- Overriding hydra default configs ----------
hydra:
  job:
    name: train
    chdir: true
  run:
    dir: output/${hydra.job.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}

defaults:
  - _self_
  - dir: dir

n_epochs: 75
img_size: 384
model_name: "tf_efficientnet_b5"
checkpoint_path: "/kaggle/input/tf-efficientnet/pytorch/tf-efficientnet-b5/1/tf_efficientnet_b5_ra-9a3e5369.pth"
train_batch_size: 16
valid_batch_size: 64
scheduler: "CosineAnnealingLR"
lr: 1e-4
min_lr: 1e-6
T_max: 500
weight_decay: 1e-6
fold: 0
n_folds: 5
n_accumulates: 1

