# ---------- Overriding hydra default configs ----------
hydra:
  job:
    name: train
    chdir: true
  run:
    dir: output/${hydra.job.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}

defaults:
  - _self_
  - dir: dir

n_epochs: 40
img_size: 336
model_name: "eva02_small_patch14_336.mim_in22k_ft_in1k"
train_batch_size: 64
valid_batch_size: 64
scheduler: "CosineAnnealingLR"
lr: 1e-4
min_lr: 1e-6
T_max: 500
weight_decay: 1e-6
fold: 0
n_folds: 5
n_accumulates: 1

